const NETSCAPE_HEADER = [
    '# Netscape HTTP Cookie File',
    '# This file was generated by Nora. Edit at your own risk.',
    '',
].join('\n');
const cleanCookieField = (value) => value.replace(/[\t\r\n]/g, '');
export function formatProfileCookiesTxt(cookies) {
    const rows = cookies.flatMap((cookie) => {
        const rawDomain = cleanCookieField(cookie.domain.trim());
        const path = cleanCookieField(cookie.path.trim()) || '/';
        const name = cleanCookieField(cookie.name.trim());
        const value = cleanCookieField(cookie.value);
        if (!rawDomain || !name)
            return [];
        const includeSubdomains = rawDomain.startsWith('.');
        const domain = cookie.httpOnly ? `#HttpOnly_${rawDomain}` : rawDomain;
        const expires = Number.isFinite(cookie.expires) ? Math.max(0, Math.floor(cookie.expires)) : 0;
        return [
            `${domain}\t${includeSubdomains ? 'TRUE' : 'FALSE'}\t${path}\t${cookie.secure ? 'TRUE' : 'FALSE'}\t${expires}\t${name}\t${value}`,
        ];
    });
    return rows.length ? `${NETSCAPE_HEADER}${rows.join('\n')}\n` : '';
}
export function formatCookiesTxt(cookieHeader, url) {
    const target = new URL(url);
    const domain = target.hostname;
    const secure = target.protocol === 'https:' ? 'TRUE' : 'FALSE';
    const rows = cookieHeader
        .split(';')
        .map((item) => item.trim())
        .filter(Boolean)
        .flatMap((item) => {
        const separator = item.indexOf('=');
        if (separator <= 0)
            return [];
        const name = cleanCookieField(item.slice(0, separator).trim());
        const value = cleanCookieField(item.slice(separator + 1));
        if (!name)
            return [];
        return [`${domain}\tFALSE\t/\t${secure}\t0\t${name}\t${value}`];
    });
    return rows.length ? `${NETSCAPE_HEADER}${rows.join('\n')}\n` : '';
}
