name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 24 Environment
        uses: actions/setup-node@v4
        with:
          node-version: 24 # التوافق الكامل والوحيد المقبول في خوادم 2026

      - name: Install Bun Toolchain
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Clean App Dependency Installation
        run: |
          npm install -g bun
          bun install --no-frozen-lockfile --ignore-scripts

      - name: Compile and Export Production Android App
        run: |
          npx expo export --platform android
